### ISSUE TITLE
Suggestion: Don't depend on a premium plugin. Your making us pay someone else to use this.

### ISSUE THREAD

**Issue by EnderBro123** [mVabo/VeryDangerousNether#1]

**Comment by mVabo** [comment]
Hello, you don't need the premium version of this plugin to run it :) You can actually download the free version over here: https://ci.md-5.net/job/LibsDisguises/

The other dependency can be downloaded (for free) over here:
https://ci.dmulloy2.net/job/ProtocolLib/

**Comment by EnderBro123** [comment]
Oh. Doesn't the Development builds not support 1.13+ versions? May be wrong somehow but just wondering.

**Comment by mVabo** [comment]
All versions after 2.x.x supports 1.16+
All versions marked with 1.x.x supports 1.15+
All versions made by EvilLootly is made for 1.13/1.14

**Comment by EnderBro123** [comment]
Oh.
